# theme.py
# Module de gestion de thèmes pour l'application Flask
# Permet de définir jusqu'à 10 thèmes personnalisables

from flask import session, current_app

# Définition des thèmes :
# Chaque thème est un dict de variables CSS (--var-name : valeur).
# Ajout de couleurs pour les états de survol (_dark) et ajustement des couleurs de texte pour les boutons.
THEMES = {
    "turquoise": {
        "bg-color": "#e0f7fa", # Un fond plus clair pour le thème turquoise
        "text-color": "#0b3c5d",
        "primary-color": "#0d9488",
        "secondary-color": "#1a73e8",
        "button-bg": "#0d9488",
        "button-text": "#ffffff",
        "card-bg": "#ffffff",
        "card-shadow": "rgba(0, 60, 100, 0.1)",
        "success-color": "#28a745",
        "success-color-dark": "#218838",
        "warning-color": "#ffc107",
        "warning-color-dark": "#e0a800",
        "danger-color": "#dc3545",
        "danger-color-dark": "#c82333",
        "info-color": "#17a2b8",
        "info-color-dark": "#138496",
        "secondary-color-dark": "#135cb8", # Une variante plus foncée pour le survol
        "text-color-light": "#6c757d", # Couleur de texte plus claire pour les labels flottants
        "table-striped-bg": "#f8f9fa", # Couleur pour les lignes impaires du tableau
        "border-color": "#dee2e6", # Couleur de bordure pour les tableaux
        "primary-color-rgb": "13, 148, 136", # RGB pour les ombres et les états de focus
        "secondary-color-rgb": "26, 115, 232",
    },
    "deep_ocean": {
        "bg-color": "#e0f2f7",
        "text-color": "#001a33",
        "primary-color": "#000080",
        "secondary-color": "#4682B4",
        "button-bg": "#000080",
        "button-text": "#ffffff",
        "card-bg": "#ffffff",
        "card-shadow": "rgba(0, 0, 128, 0.2)",
        "success-color": "#28a745",
        "success-color-dark": "#218838",
        "warning-color": "#ffc107",
        "warning-color-dark": "#e0a800",
        "danger-color": "#dc3545",
        "danger-color-dark": "#c82333",
        "info-color": "#17a2b8",
        "info-color-dark": "#138496",
        "secondary-color-dark": "#3a6994",
        "text-color-light": "#6c757d",
        "table-striped-bg": "#f8f9fa",
        "border-color": "#dee2e6",
        "primary-color-rgb": "0, 0, 128",
        "secondary-color-rgb": "70, 130, 180",
    },
    "rose": {
        "bg-color": "#fdf2f8",
        "text-color": "#831843",
        "primary-color": "#db2777",
        "secondary-color": "#be185d",
        "button-bg": "#db2777",
        "button-text": "#ffffff",
        "card-bg": "#ffffff",
        "card-shadow": "rgba(219, 39, 119, 0.2)",
        "success-color": "#28a745",
        "success-color-dark": "#218838",
        "warning-color": "#ffc107",
        "warning-color-dark": "#e0a800",
        "danger-color": "#dc3545",
        "danger-color-dark": "#c82333",
        "info-color": "#17a2b8",
        "info-color-dark": "#138496",
        "secondary-color-dark": "#a1154e",
        "text-color-light": "#6c757d",
        "table-striped-bg": "#f8f9fa",
        "border-color": "#dee2e6",
        "primary-color-rgb": "219, 39, 119",
        "secondary-color-rgb": "190, 24, 93",
    },
    "warm_sunset": {
        "bg-color": "#fff3e0",
        "text-color": "#8b4513",
        "primary-color": "#FF7F50",
        "secondary-color": "#FFD700",
        "button-bg": "#FF7F50",
        "button-text": "#ffffff",
        "card-bg": "#ffffff",
        "card-shadow": "rgba(255, 127, 80, 0.2)",
        "success-color": "#28a745",
        "success-color-dark": "#218838",
        "warning-color": "#ffc107",
        "warning-color-dark": "#e0a800",
        "danger-color": "#dc3545",
        "danger-color-dark": "#c82333",
        "info-color": "#17a2b8",
        "info-color-dark": "#138496",
        "secondary-color-dark": "#e0c000",
        "text-color-light": "#6c757d",
        "table-striped-bg": "#f8f9fa",
        "border-color": "#dee2e6",
        "primary-color-rgb": "255, 127, 80",
        "secondary-color-rgb": "255, 215, 0",
    },
    "light": {
        "bg-color":      "#f5f9ff",
        "text-color":    "#0b3c5d",
        "primary-color": "#1e81b0",
        "secondary-color":"#a7c5eb",
        "button-bg":     "#1e81b0",
        "button-text":   "#ffffff",
        "card-bg":       "#ffffff",
        "card-shadow":   "rgba(0, 60, 100, 0.1)",
        "success-color": "#28a745",
        "success-color-dark": "#218838",
        "warning-color": "#ffc107",
        "warning-color-dark": "#e0a800",
        "danger-color": "#dc3545",
        "danger-color-dark": "#c82333",
        "info-color": "#17a2b8",
        "info-color-dark": "#138496",
        "secondary-color-dark": "#8dafd1",
        "text-color-light": "#6c757d",
        "table-striped-bg": "#f8f9fa",
        "border-color": "#dee2e6",
        "primary-color-rgb": "30, 129, 176",
        "secondary-color-rgb": "167, 197, 235",
    },
    "dark": {
        "bg-color":      "#0b3c5d",
        "text-color":    "#ffffff",
        "primary-color": "#3da5d9",
        "secondary-color":"#6ebfea",
        "button-bg":     "#3da5d9",
        "button-text":   "#ffffff",
        "card-bg":       "#1f2833",
        "card-shadow":   "rgba(61, 165, 217, 0.2)",
        "success-color": "#28a745",
        "success-color-dark": "#218838",
        "warning-color": "#ffc107",
        "warning-color-dark": "#e0a800",
        "danger-color": "#dc3545",
        "danger-color-dark": "#c82333",
        "info-color": "#17a2b8",
        "info-color-dark": "#138496",
        "secondary-color-dark": "#5a9fc2",
        "text-color-light": "#adb5bd",
        "table-striped-bg": "#2a3744",
        "border-color": "#495057",
        "primary-color-rgb": "61, 165, 217",
        "secondary-color-rgb": "110, 191, 234",
    },
    "ocean": {
        "bg-color":      "#e0f7fa",
        "text-color":    "#004d40",
        "primary-color": "#00796b",
        "secondary-color":"#b2dfdb",
        "button-bg":     "#00796b",
        "button-text":   "#ffffff",
        "card-bg":       "#ffffff",
        "card-shadow":   "rgba(0, 121, 107, 0.2)",
        "success-color": "#28a745",
        "success-color-dark": "#218838",
        "warning-color": "#ffc107",
        "warning-color-dark": "#e0a800",
        "danger-color": "#dc3545",
        "danger-color-dark": "#c82333",
        "info-color": "#17a2b8",
        "info-color-dark": "#138496",
        "secondary-color-dark": "#98c9c6",
        "text-color-light": "#6c757d",
        "table-striped-bg": "#f8f9fa",
        "border-color": "#dee2e6",
        "primary-color-rgb": "0, 121, 107",
        "secondary-color-rgb": "178, 223, 219",
    },
    "sunset": {
        "bg-color":      "#fff8e1",
        "text-color":    "#bf360c",
        "primary-color": "#e65100",
        "secondary-color":"#ffab40",
        "button-bg":     "#e65100",
        "button-text":   "#ffffff",
        "card-bg":       "#ffffff",
        "card-shadow":   "rgba(230, 81, 0, 0.2)",
        "success-color": "#28a745",
        "success-color-dark": "#218838",
        "warning-color": "#ffc107",
        "warning-color-dark": "#e0a800",
        "danger-color": "#dc3545",
        "danger-color-dark": "#c82333",
        "info-color": "#17a2b8",
        "info-color-dark": "#138496",
        "secondary-color-dark": "#e0932a",
        "text-color-light": "#6c757d",
        "table-striped-bg": "#f8f9fa",
        "border-color": "#dee2e6",
        "primary-color-rgb": "230, 81, 0",
        "secondary-color-rgb": "255, 171, 64",
    },
    "forest": {
        "bg-color":      "#e8f5e9",
        "text-color":    "#1b5e20",
        "primary-color": "#2e7d32",
        "secondary-color":"#a5d6a7",
        "button-bg":     "#2e7d32",
        "button-text":   "#ffffff",
        "card-bg":       "#ffffff",
        "card-shadow":   "rgba(46, 125, 50, 0.2)",
        "success-color": "#28a745",
        "success-color-dark": "#218838",
        "warning-color": "#ffc107",
        "warning-color-dark": "#e0a800",
        "danger-color": "#dc3545",
        "danger-color-dark": "#c82333",
        "info-color": "#17a2b8",
        "info-color-dark": "#138496",
        "secondary-color-dark": "#8cb38e",
        "text-color-light": "#6c757d",
        "table-striped-bg": "#f8f9fa",
        "border-color": "#dee2e6",
        "primary-color-rgb": "46, 125, 50",
        "secondary-color-rgb": "165, 214, 167",
    },
    "slate": {
        "bg-color": "#f8fafc",
        "text-color": "#0f172a",
        "primary-color": "#64748b",
        "secondary-color": "#475569",
        "button-bg": "#64748b",
        "button-text": "#ffffff",
        "card-bg": "#ffffff",
        "card-shadow": "rgba(71, 84, 105, 0.1)",
        "success-color": "#28a745",
        "success-color-dark": "#218838",
        "warning-color": "#ffc107",
        "warning-color-dark": "#e0a800",
        "danger-color": "#dc3545",
        "danger-color-dark": "#c82333",
        "info-color": "#17a2b8",
        "info-color-dark": "#138496",
        "secondary-color-dark": "#3a4756",
        "text-color-light": "#6c757d",
        "table-striped-bg": "#f8f9fa",
        "border-color": "#dee2e6",
        "primary-color-rgb": "100, 116, 139",
        "secondary-color-rgb": "71, 85, 105",
    },
    "sunrise": {
        "bg-color": "#fffbeb",
        "text-color": "#78350f",
        "primary-color": "#f59e0b",
        "secondary-color": "#d97706",
        "button-bg": "#f59e0b",
        "button-text": "#ffffff",
        "card-bg": "#ffffff",
        "card-shadow": "rgba(245, 158, 11, 0.2)",
        "success-color": "#28a745",
        "success-color-dark": "#218838",
        "warning-color": "#ffc107",
        "warning-color-dark": "#e0a800",
        "danger-color": "#dc3545",
        "danger-color-dark": "#c82333",
        "info-color": "#17a2b8",
        "info-color-dark": "#138496",
        "secondary-color-dark": "#b86a05",
        "text-color-light": "#6c757d",
        "table-striped-bg": "#f8f9fa",
        "border-color": "#dee2e6",
        "primary-color-rgb": "245, 158, 11",
        "secondary-color-rgb": "217, 119, 6",
    },
    "violet": {
        "bg-color": "#f5f3ff",
        "text-color": "#3730a3",
        "primary-color": "#7c3aed",
        "secondary-color": "#6d28d9",
        "button-bg": "#7c3aed",
        "button-text": "#ffffff",
        "card-bg": "#ffffff",
        "card-shadow": "rgba(124, 58, 237, 0.2)",
        "success-color": "#28a745",
        "success-color-dark": "#218838",
        "warning-color": "#ffc107",
        "warning-color-dark": "#e0a800",
        "danger-color": "#dc3545",
        "danger-color-dark": "#c82333",
        "info-color": "#17a2b8",
        "info-color-dark": "#138496",
        "secondary-color-dark": "#5f29b8",
        "text-color-light": "#6c757d",
        "table-striped-bg": "#f8f9fa",
        "border-color": "#dee2e6",
        "primary-color-rgb": "124, 58, 237",
        "secondary-color-rgb": "109, 40, 217",
    },
    "emerald": {
        "bg-color": "#ecfdf5",
        "text-color": "#065f46",
        "primary-color": "#10b981",
        "secondary-color": "#047857",
        "button-bg": "#10b981",
        "button-text": "#ffffff",
        "card-bg": "#ffffff",
        "card-shadow": "rgba(16, 185, 129, 0.2)",
        "success-color": "#28a745",
        "success-color-dark": "#218838",
        "warning-color": "#ffc107",
        "warning-color-dark": "#e0a800",
        "danger-color": "#dc3545",
        "danger-color-dark": "#c82333",
        "info-color": "#17a2b8",
        "info-color-dark": "#138496",
        "secondary-color-dark": "#03664a",
        "text-color-light": "#6c757d",
        "table-striped-bg": "#f8f9fa",
        "border-color": "#dee2e6",
        "primary-color-rgb": "16, 185, 129",
        "secondary-color-rgb": "4, 120, 87",
    },
    "royal_blue": {
        "bg-color": "#e6f0ff",
        "text-color": "#002060",
        "primary-color": "#4169E1",
        "secondary-color": "#87CEEB",
        "button-bg": "#4169E1",
        "button-text": "#ffffff",
        "card-bg": "#ffffff",
        "card-shadow": "rgba(65, 105, 225, 0.2)",
        "success-color": "#28a745",
        "success-color-dark": "#218838",
        "warning-color": "#ffc107",
        "warning-color-dark": "#e0a800",
        "danger-color": "#dc3545",
        "danger-color-dark": "#c82333",
        "info-color": "#17a2b8",
        "info-color-dark": "#138496",
        "secondary-color-dark": "#6a9acd",
        "text-color-light": "#6c757d",
        "table-striped-bg": "#f8f9fa",
        "border-color": "#dee2e6",
        "primary-color-rgb": "65, 105, 225",
        "secondary-color-rgb": "135, 206, 235",
    },
}

# Valeur par défaut
DEFAULT_THEME = "turquoise"

def get_theme(name: str) -> dict:
    """Retourne le dict de variables CSS pour un thème donné."""
    return THEMES.get(name, THEMES[DEFAULT_THEME])

def current_theme() -> dict:
    """Récupère le thème courant depuis la session Flask."""
    theme_name = session.get('theme', DEFAULT_THEME)
    return get_theme(theme_name)

def init_theme(app):
    """Enregistre le context_processor pour injecter les variables de thème dans les templates."""
    @app.context_processor
    def inject_theme_vars():
        return {'theme_vars': current_theme()}

    # Endpoint pour changer de thème
    @app.route('/set_theme/<name>')
    def set_theme(name):
        if name in THEMES:
            session['theme'] = name
        return ('', 204)